### ISSUE TITLE
Integration issue

### ISSUE THREAD

**Issue by UltraEngine** [melax/sandbox#5]
Hi, I am attempting to integrate the bunny LOD code into my program, but all it does is delete some triangles from the mesh. If I set the render number to the number of vertices (no reduction), the resulting mesh looks identical to the original.

I don't see anything wrong in my code, compared to the example. Do you see any obvious mistakes? Thanks.
```
int Map(const std::vector<int>& collapse_map, int a, int mx) {
	if (mx <= 0) return 0;
	while (a >= mx) {
		a = collapse_map[a];
	}
	return a;
}
```
```
//-----------------------------
// Get mesh data
//-----------------------------

std::vector<linalg::aliases::float3> vert;
std::vector<tridata> tri;
std::vector<int> map;
std::vector<int> permutation;
tridata t;

for (const auto& v : mesh->vertices)
{
	vert.push_back(linalg::aliases::float3(v.position.x, v.position.y, v.position.z));
}

for (int n = 0; n < mesh->CountPrimitives(); ++n)
{
	t.v[0] = mesh->GetPrimitiveVertex(n, 0);
	t.v[1] = mesh->GetPrimitiveVertex(n, 1);
	t.v[2] = mesh->GetPrimitiveVertex(n, 2);
	tri.push_back(t);
}

//-----------------------------
// Reduce the mesh
//-----------------------------

ProgressiveMesh(vert, tri, map, permutation);
				
//-----------------------------
// PermuteVertices
//-----------------------------
				
// rearrange the vertex Array 
std::vector<float3> temp_Array;
unsigned int i;
assert(permutation.size() == vert.size());
for (i = 0; i < vert.size(); i++) {
	temp_Array.push_back(vert[i]);
}
for (i = 0; i < vert.size(); i++) {
	vert[permutation[i]] = temp_Array[i];
}
// update the changes in the entries in the triangle Array
for (i = 0; i < tri.size(); i++) {
	for (int j = 0; j < 3; j++) {
		tri[i].v[j] = permutation[tri[i].v[j]];
	}
}

//-----------------------------
// Build new mesh
//-----------------------------

Assert(map.size());
model->Clear();
mesh = model->AddMesh();

// Add all vertices - this can be improved later
for (int i = 0; i < vert.size(); ++i)
{
	mesh->AddVertex(vert[i].x, vert[i].y, vert[i].z);
}

//Add triangles
int render_num = vert.size() * 0.5;
for (unsigned int i = 0; i < tri.size(); i++)
{
	int p0 = Map(map, tri[i].v[0], render_num);
	int p1 = Map(map, tri[i].v[1], render_num);
	int p2 = Map(map, tri[i].v[2], render_num);
	if (p0 == p1 or p1 == p2 or p2 == p0) continue;
	mesh->AddPrimitive(p0, p1, p2);
}
```

**Comment by UltraEngine** [comment]
I also did have to make some changes to misc.h for compatibility with C++17:
```
//template<typename F, typename S> auto Transform(std::vector<S>& src, F f) { std::vector<std::result_of_t<F(S)>> dst; dst.reserve(src.size()); std::transform(src.begin(), src.end(), std::back_inserter(dst), f); return dst; }
//template<typename F, typename S> auto Transform(const std::vector<S> &src, F f) { std::vector<std::result_of_t<F(S)>> dst;dst.reserve(src.size()); std::transform(src.begin(), src.end(), std::back_inserter(dst), f); return dst; }

template<typename F, typename S>
auto Transform(std::vector<S>& src, F f)
{
	std::vector<std::invoke_result_t<F, S> > dst;
	dst.reserve(src.size());
	std::transform(src.begin(), src.end(), std::back_inserter(dst), f);
	return dst;
}

template<typename F, typename S> auto Transform(const std::vector<S>& src, F f)
{
	std::vector<std::invoke_result_t<F, S> > dst;
	dst.reserve(src.size()); 
	std::transform(src.begin(), src.end(), std::back_inserter(dst), f);
	return dst;
}
```

**Comment by melax** [comment]
are you trying the new code on the bunny mesh that was included with the example?   or a different mesh?    
this edge-collapse algorithm is pretty simple, but it expects a manifold indexed-triangle mesh (adjacent triangles sharing vertex indices) so when it collapses triangles, the adjacent triangles tend to fill in the boundary.  

I cant tell from the following code :
`t.v[0] = mesh->GetPrimitiveVertex(n, 0);
	t.v[1] = mesh->GetPrimitiveVertex(n, 1);
	t.v[2] = mesh->GetPrimitiveVertex(n, 2);`
what data is getting fed into the algo.   if neighboring triangles share an edge, and hence two corners.  however,  do they share two vertices, where vertices may have been split to support different normals, texture coords, color, etc.


admittedly, the code in the original repo is a bit dated, but it seems to still compile in visual studio c++ 17 with conformance mode.   one annoying thing is the upper right close window widget doesn't work, but double clicking on the upper left closes the window.

**Comment by UltraEngine** [comment]
I was able to compile and run the original code with C++17, and it appears to work correctly.

> are you trying the new code on the bunny mesh that was included with the example? or a different mesh? this edge-collapse algorithm is pretty simple, but it expects a manifold indexed-triangle mesh (adjacent triangles sharing vertex indices) so when it collapses triangles, the adjacent triangles tend to fill in the boundary.

That explanation actually does fit the description of what I am seeing. It actually appears sections of the mesh are disappearing along a UV seam, where adjacent triangles do not share the same vertex. So I guess all the vertices need to be "welded" together before running this algorithm. How would you suggest the UV coordinates and normals be preserved?

![ezgif-3-d6e037f7c2](https://github.com/melax/sandbox/assets/64279130/079280b8-cdfa-453e-a10e-b638a9d4186a)

> I cant tell from the following code : `t.v[0] = mesh->GetPrimitiveVertex(n, 0); t.v[1] = mesh->GetPrimitiveVertex(n, 1); t.v[2] = mesh->GetPrimitiveVertex(n, 2);` what data is getting fed into the algo. if neighboring triangles share an edge, and hence two corners. however, do they share two vertices, where vertices may have been split to support different normals, texture coords, color, etc.

Mesh::GetPrimitiveVertex() just retrieves the vertex index for a given primitive, in this case triangles.
